# Generated by Django 5.1.3 on 2025-05-10 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_populate_departments'),
        ('inventory', '0004_alter_employee_position'),
    ]

    operations = [
    ]
