# Generated by Django 5.1.3 on 2025-05-10 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_department_options_alter_employee_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['first_name', 'last_name'], 'verbose_name': 'Employee', 'verbose_name_plural': 'Employees'},
        ),
        migrations.AddField(
            model_name='employee',
            name='company',
            field=models.CharField(choices=[('ACD', 'ACD'), ('CTP', 'CTP')], default='ACD', max_length=3),
        ),
    ]
