# Generated by Django 5.1.3 on 2025-05-10 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_employee_options_employee_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='national_id',
            field=models.CharField(blank=True, help_text='Enter the 14-digit national ID number', max_length=14, null=True, unique=True),
        ),
    ]
