# Generated by Django 5.1.3 on 2025-05-12 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_employee_national_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itasset',
            name='delivery_letter_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='itasset',
            name='hdd1_capacity',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='itasset',
            name='hdd2_capacity',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='itasset',
            name='hdd_type',
            field=models.CharField(choices=[('ssd', 'SSD'), ('hdd', 'HDD'), ('nvme', 'NVMe'), ('other', 'Other')], default='other', max_length=10),
        ),
        migrations.AddField(
            model_name='itasset',
            name='host_name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='itasset',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='itasset',
            name='mac_address_ethernet',
            field=models.CharField(blank=True, max_length=17, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='itasset',
            name='mac_address_wifi',
            field=models.CharField(blank=True, max_length=17, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='itasset',
            name='owner',
            field=models.CharField(choices=[('aman', 'Aman'), ('ctp', 'CTP'), ('misr_assist', 'Misr Assist')], default='aman', max_length=20),
        ),
        migrations.AddField(
            model_name='itasset',
            name='processor',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='itasset',
            name='ram_size',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='itasset',
            name='ram_type',
            field=models.CharField(choices=[('ddr3', 'DDR3'), ('ddr4', 'DDR4'), ('ddr5', 'DDR5'), ('other', 'Other')], default='other', max_length=10),
        ),
    ]
