# Generated by Django 5.1.3 on 2025-05-12 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_itasset_connection_type_itasset_ink_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itasset',
            name='ink_status',
        ),
        migrations.AddField(
            model_name='itasset',
            name='printer_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='printers', to='inventory.department'),
        ),
        migrations.AddField(
            model_name='itasset',
            name='printer_responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_printers', to='inventory.employee'),
        ),
    ]
