# Generated by Django 5.1.3 on 2025-05-12 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_remove_itasset_ink_status_itasset_printer_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itasset',
            name='battery_health',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='itasset',
            name='duplex_printing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='itasset',
            name='graphics_card',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='itasset',
            name='imei_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='itasset',
            name='operating_system',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='itasset',
            name='os_version',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='itasset',
            name='panel_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='itasset',
            name='paper_size_support',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='itasset',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='itasset',
            name='refresh_rate',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='itasset',
            name='resolution',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='itasset',
            name='screen_protection',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='itasset',
            name='screen_size',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='itasset',
            name='sim_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='itasset',
            name='storage_capacity',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='itasset',
            name='toner_cartridge_model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='itasset',
            name='hdd1_capacity',
            field=models.CharField(blank=True, default='0', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='itasset',
            name='hdd_type',
            field=models.CharField(blank=True, choices=[('ssd', 'SSD'), ('hdd', 'HDD'), ('nvme', 'NVMe'), ('other', 'Other')], default='other', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='itasset',
            name='processor',
            field=models.CharField(blank=True, default='Unknown', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='itasset',
            name='ram_size',
            field=models.CharField(blank=True, default='0', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='itasset',
            name='ram_type',
            field=models.CharField(blank=True, choices=[('ddr3', 'DDR3'), ('ddr4', 'DDR4'), ('ddr5', 'DDR5'), ('other', 'Other')], default='other', max_length=10, null=True),
        ),
    ]
