# Generated by Django 5.1.3 on 2025-05-12 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_itasset_hdd1_capacity_itasset_hdd2_capacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itasset',
            name='delivery_letter_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='itasset',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, protocol='IPv4'),
        ),
        migrations.AddField(
            model_name='itasset',
            name='mac_address_ethernet',
            field=models.CharField(blank=True, help_text='Format: XX:XX:XX:XX:XX:XX', max_length=17, null=True),
        ),
        migrations.AddField(
            model_name='itasset',
            name='mac_address_wifi',
            field=models.CharField(blank=True, help_text='Format: XX:XX:XX:XX:XX:XX', max_length=17, null=True),
        ),
        migrations.AddField(
            model_name='itasset',
            name='receipt_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
