# Generated by Django 5.1.3 on 2025-05-21 17:44

from django.db import migrations, models

def create_owner_companies(apps, schema_editor):
    OwnerCompany = apps.get_model('inventory', 'OwnerCompany')
    
    # Create initial owner companies
    owner_companies = [
        ('AMAN', 'Aman'),
        ('CTP', 'CTP'),
        ('MISR_ASSIST', 'Misr Assist'),
    ]

    for code, name in owner_companies:
        OwnerCompany.objects.get_or_create(
            code=code,
            defaults={'name': name}
        )

class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0029_company_alter_employee_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Owner Company',
                'verbose_name_plural': 'Owner Companies',
                'ordering': ['name'],
            },
        ),
        migrations.RunPython(create_owner_companies),
    ]
