# Generated by Django 5.1.3 on 2025-05-25 07:17

from django.db import migrations

def fix_phone_numbers(apps, schema_editor):
    Employee = apps.get_model('inventory', 'Employee')
    # Update all null phone numbers to empty string
    Employee.objects.filter(phone_number__isnull=True).update(phone_number='')

def reverse_fix_phone_numbers(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0032_alter_employee_phone_number'),
    ]

    operations = [
        migrations.RunPython(fix_phone_numbers, reverse_fix_phone_numbers),
    ]
