# Generated by Django 5.1.3 on 2025-05-25 07:18

from django.db import migrations, models

def forward_func(apps, schema_editor):
    Employee = apps.get_model('inventory', 'Employee')
    # Replace NULL values with empty string
    Employee.objects.filter(phone_number__isnull=True).update(phone_number='')

def reverse_func(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0033_fix_phone_numbers'),
    ]

    operations = [
        # Step 1: Modify the field to allow nulls temporarily
        migrations.AlterField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(max_length=17, null=True, blank=True),
        ),
        # Step 2: Update all null values to empty string
        migrations.RunPython(forward_func, reverse_func),
        # Step 3: Add back the constraints and validation
        migrations.AlterField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(
                max_length=17,
                blank=True,
                default='',
                help_text="Enter phone number in the format: '+999999999'"
            ),
        ),
    ]
