# Generated by Django 5.1.3 on 2025-05-26 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('inventory', '0052_add_default_notification_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='is_email_sent',
        ),
        migrations.AlterField(
            model_name='notification',
            name='action_url',
            field=models.URLField(blank=True, null=True, verbose_name='Action URL'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='inventory.notificationcategory', verbose_name='Category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='object_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['content_type', 'object_id'], name='inventory_n_content_41af1e_idx'),
        ),
    ]
