# Generated by Django 5.1.3 on 2025-05-31 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0036_delete_and_create_notification'),
        ('inventory', '0055_create_default_notification_categories'),
        ('inventory', '0055_fix_notification_schema'),
    ]

    operations = [
    ]
