# Generated by Django 5.2.4 on 2025-07-16 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_employee_is_active_alter_employee_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itasset',
            options={'ordering': ['name'], 'permissions': [('can_backup_database', 'Can backup database')], 'verbose_name': 'IT Asset', 'verbose_name_plural': 'IT Assets'},
        ),
    ]
