# Generated by Django 5.2.1 on 2025-07-17 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_add_database_backup_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownercompany',
            name='name',
            field=models.CharField(choices=[('ARCORP', 'ARCORP'), ('مصنع القاهره', 'مصنع القاهره للمنتجات المروريه'), ('أمان استثمار', 'أمان استثمار'), ('أمان تحصيل', 'أمان تحصيل')], max_length=100),
        ),
    ]
