# Generated by Django 5.2.1 on 2025-07-17 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_ownercompany_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='itasset',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Purchase price of the asset', max_digits=10, null=True),
        ),
    ]
