# Generated by Django 5.2.1 on 2025-07-17 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_itasset_purchase_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownercompany',
            name='name',
            field=models.CharField(choices=[('ACD', 'ACD'), ('AMAN E-Collection', 'AMAN E-Collection'), ('AMAN invetement', 'AMAN invetement'), ('Arcop', 'Arcop'), ('CTP', 'CTP'), ('MISR_ASSIST', 'Misr Assist')], max_length=100),
        ),
    ]
