# Generated by Django 5.1.3 on 2025-05-10 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_merge_20250510_1327'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['name'], 'verbose_name': 'Department', 'verbose_name_plural': 'Departments'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Employee', 'verbose_name_plural': 'Employees'},
        ),
        migrations.AlterModelOptions(
            name='itasset',
            options={'ordering': ['-created_at'], 'verbose_name': 'IT Asset', 'verbose_name_plural': 'IT Assets'},
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(choices=[('warehouse', 'Warehouse'), ('hr', 'HR'), ('procurement', 'Procurement'), ('quality', 'Quality'), ('finance', 'Finance'), ('production', 'Production'), ('maintenance', 'Maintenance'), ('osh', 'Occupational Safety and Health'), ('it', 'IT')], max_length=100, unique=True),
        ),
    ]
