# Generated by Django 5.2.1 on 2025-07-17 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_ownercompany_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itasset',
            name='purchase_price',
        ),
    ]
