# Generated by Django 5.2.1 on 2025-07-18 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_remove_itasset_purchase_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outlet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('full_address', models.TextField(verbose_name='Full Address')),
                ('google_maps_url', models.URLField(blank=True, null=True, verbose_name='Google Maps URL')),
                ('network_subnet', models.CharField(blank=True, max_length=18, null=True, verbose_name='Network Subnet')),
                ('gateway_ip', models.GenericIPAddressField(blank=True, null=True, protocol='IPv4', verbose_name='Gateway IP')),
                ('dns_servers', models.CharField(blank=True, max_length=255, null=True, verbose_name='DNS Servers')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outlets', to='inventory.ownercompany')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_outlets', to='inventory.employee', verbose_name='Manager')),
                ('responsible_employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_for_outlets', to='inventory.employee', verbose_name='Responsible Employee')),
            ],
            options={
                'verbose_name': 'Outlet',
                'verbose_name_plural': 'Outlets',
                'ordering': ['name'],
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('type', models.CharField(choices=[('ethernet', 'Ethernet'), ('fiber', 'Fiber'), ('other', 'Other')], default='ethernet', max_length=20, verbose_name='Type')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, protocol='IPv4', verbose_name='IP Address')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('error', 'Error')], default='inactive', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('connected_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connected_ports', to='inventory.itasset')),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ports', to='inventory.outlet')),
            ],
            options={
                'verbose_name': 'Port',
                'verbose_name_plural': 'Ports',
                'ordering': ['name'],
                'unique_together': {('outlet', 'name')},
            },
        ),
    ]
