# Generated by Django 5.2.1 on 2025-07-19 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_itasset_outlet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownercompany',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
