# Generated by Django 5.2.1 on 2025-07-22 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_ownercompany_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itasset',
            name='delivery_letter_code',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
