# Generated by Django 5.1.3 on 2025-05-12 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_itasset_delivery_letter_code_itasset_hdd1_capacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itasset',
            name='receipt_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
