# Generated by Django 5.1.3 on 2025-05-12 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_itasset_receipt_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='itasset',
            name='connection_type',
            field=models.CharField(blank=True, choices=[('usb', 'USB'), ('wifi', 'Wi-Fi'), ('network', 'Network')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='itasset',
            name='ink_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='itasset',
            name='last_maintenance_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itasset',
            name='printer_type',
            field=models.CharField(blank=True, choices=[('laser', 'Laser'), ('ink', 'Ink'), ('3d', '3D')], max_length=10, null=True),
        ),
    ]
