# Generated by Django 5.2.1 on 2025-07-22 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_alter_itasset_delivery_letter_code'),
    ]

    operations = [
    ]
