# Generated by Django 5.2.1 on 2025-07-22 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_update_delivery_codes'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_number', models.IntegerField(default=0)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sequence', to='inventory.ownercompany')),
            ],
            options={
                'verbose_name': 'Company Sequence',
                'verbose_name_plural': 'Company Sequences',
            },
        ),
    ]
