# Generated by Django 5.2.1 on 2025-07-22 06:35

from django.db import migrations
import re

def initialize_sequences(apps, schema_editor):
    ITAsset = apps.get_model('inventory', 'ITAsset')
    OwnerCompany = apps.get_model('inventory', 'OwnerCompany')
    CompanySequence = apps.get_model('inventory', 'CompanySequence')

    # For each company
    for company in OwnerCompany.objects.all():
        # Get all assets for this company
        assets = ITAsset.objects.filter(owner=company)
        max_number = 0

        # Find the highest number in existing delivery codes
        for asset in assets:
            if asset.delivery_letter_code:
                match = re.match(rf"{company.code}-(\d+)", asset.delivery_letter_code)
                if match:
                    number = int(match.group(1))
                    max_number = max(max_number, number)

        # Create or update sequence
        CompanySequence.objects.update_or_create(
            company=company,
            defaults={'last_number': max_number}
        )

class Migration(migrations.Migration):
    dependencies = [
        ('inventory', '0014_companysequence'),
    ]

    operations = [
        migrations.RunPython(initialize_sequences, reverse_code=migrations.RunPython.noop),
    ]
