# Generated by Django 5.1.3 on 2025-05-12 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_rename_last_maintenance_date_itasset_ups_battery_replacement_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itasset',
            name='owner',
            field=models.CharField(choices=[('AMAN', 'Aman'), ('CTP', 'CTP'), ('MISR_ASSIST', 'Misr Assist')], default='CTP', max_length=20),
        ),
    ]
