# Generated by Django 5.2.1 on 2025-07-28 06:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_initialize_company_sequences'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('username', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('attempt_time', models.DateTimeField(auto_now_add=True)),
                ('is_successful', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Registration Attempt',
                'verbose_name_plural': 'Registration Attempts',
                'ordering': ['-attempt_time'],
            },
        ),
        migrations.CreateModel(
            name='UserTermsAcceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms_version', models.CharField(default='1.0', max_length=10)),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='terms_acceptance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Terms Acceptance',
                'verbose_name_plural': 'User Terms Acceptances',
            },
        ),
    ]
