# Generated by Django 5.1.3 on 2025-05-12 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_add_network_and_delivery_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='itasset',
            name='connection_type',
            field=models.CharField(blank=True, choices=[('usb', 'USB'), ('network', 'Network'), ('wireless', 'Wireless'), ('bluetooth', 'Bluetooth')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='itasset',
            name='duplex_printing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='itasset',
            name='last_maintenance_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itasset',
            name='paper_size_support',
            field=models.CharField(blank=True, help_text='e.g., A4, A3, Legal', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='itasset',
            name='printer_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='printers', to='inventory.department'),
        ),
        migrations.AddField(
            model_name='itasset',
            name='printer_responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_printers', to='inventory.employee'),
        ),
        migrations.AddField(
            model_name='itasset',
            name='printer_type',
            field=models.CharField(blank=True, choices=[('laser', 'Laser'), ('inkjet', 'Inkjet'), ('dot_matrix', 'Dot Matrix'), ('thermal', 'Thermal'), ('3d', '3D Printer')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='itasset',
            name='toner_cartridge_model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
