# Generated by Django 5.1.3 on 2025-05-18 20:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('inventory', '0018_add_network_and_delivery_fields'),
        ('inventory', '0019_add_printer_specs'),
    ]

    operations = [
    ] 