# Generated by Django 5.1.3 on 2025-05-18 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_assettype_ownercompany_alter_itasset_asset_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itasset',
            options={'ordering': ['name'], 'verbose_name': 'IT Asset', 'verbose_name_plural': 'IT Assets'},
        ),
        migrations.RemoveField(
            model_name='itasset',
            name='connection_type',
        ),
        migrations.RemoveField(
            model_name='itasset',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='itasset',
            name='duplex_printing',
        ),
        migrations.RemoveField(
            model_name='itasset',
            name='hdd1_capacity',
        ),
        migrations.RemoveField(
            model_name='itasset',
            name='hdd2_capacity',
        ),
        migrations.RemoveField(
            model_name='itasset',
            name='last_maintenance_date',
        ),
        migrations.RemoveField(
            model_name='itasset',
            name='operating_system',
        ),
        migrations.RemoveField(
            model_name='itasset',
            name='os_version',
        ),
        migrations.RemoveField(
            model_name='itasset',
            name='paper_size_support',
        ),
        migrations.RemoveField(
            model_name='itasset',
            name='printer_department',
        ),
        migrations.RemoveField(
            model_name='itasset',
            name='printer_responsible',
        ),
        migrations.RemoveField(
            model_name='itasset',
            name='printer_type',
        ),
        migrations.RemoveField(
            model_name='itasset',
            name='processor',
        ),
        migrations.RemoveField(
            model_name='itasset',
            name='ram_size',
        ),
        migrations.RemoveField(
            model_name='itasset',
            name='toner_cartridge_model',
        ),
        migrations.RemoveField(
            model_name='itasset',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='itasset',
            name='ups_battery_count',
        ),
        migrations.RemoveField(
            model_name='itasset',
            name='ups_battery_life',
        ),
        migrations.RemoveField(
            model_name='itasset',
            name='ups_battery_replacement_date',
        ),
        migrations.RemoveField(
            model_name='itasset',
            name='ups_capacity',
        ),
        migrations.RemoveField(
            model_name='itasset',
            name='ups_manufacturer',
        ),
        migrations.AlterField(
            model_name='itasset',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.employee'),
        ),
        migrations.AlterField(
            model_name='itasset',
            name='delivery_letter_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='itasset',
            name='ip_address',
            field=models.CharField(blank=True, max_length=15, verbose_name='IP Address'),
        ),
        migrations.AlterField(
            model_name='itasset',
            name='mac_address_ethernet',
            field=models.CharField(blank=True, max_length=17, verbose_name='Ethernet MAC Address'),
        ),
        migrations.AlterField(
            model_name='itasset',
            name='mac_address_wifi',
            field=models.CharField(blank=True, max_length=17, verbose_name='Wi-Fi MAC Address'),
        ),
        migrations.AlterField(
            model_name='itasset',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('assigned', 'Assigned'), ('maintenance', 'Under Maintenance'), ('retired', 'Retired')], default='available', max_length=20),
        ),
    ]
