# Generated by Django 5.1.3 on 2025-05-18 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_populate_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='itasset',
            name='built_in_speakers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='itasset',
            name='connection_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='itasset',
            name='duplex_printing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='itasset',
            name='hdd1_capacity',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Primary Storage'),
        ),
        migrations.AddField(
            model_name='itasset',
            name='hdd2_capacity',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Secondary Storage'),
        ),
        migrations.AddField(
            model_name='itasset',
            name='operating_system',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='itasset',
            name='os_version',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='itasset',
            name='panel_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='itasset',
            name='paper_size_support',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='itasset',
            name='printer_department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='itasset',
            name='printer_responsible',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='itasset',
            name='printer_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='itasset',
            name='processor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='itasset',
            name='ram_size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='itasset',
            name='refresh_rate',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='itasset',
            name='resolution',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='itasset',
            name='screen_size',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='itasset',
            name='toner_cartridge_model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='itasset',
            name='ups_battery_count',
            field=models.IntegerField(blank=True, help_text='Number of batteries', null=True),
        ),
        migrations.AddField(
            model_name='itasset',
            name='ups_battery_life',
            field=models.IntegerField(blank=True, help_text='Remaining battery life in months', null=True),
        ),
        migrations.AddField(
            model_name='itasset',
            name='ups_battery_replacement_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itasset',
            name='ups_capacity',
            field=models.IntegerField(blank=True, help_text='Capacity in VA', null=True),
        ),
        migrations.AddField(
            model_name='itasset',
            name='ups_manufacturer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='itasset',
            name='vesa_mount',
            field=models.BooleanField(default=False),
        ),
    ]
