# Generated by Django 5.1.3 on 2025-05-22 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0030_notification_workflow'),
        ('inventory', '0032_alter_employee_phone_nullable'),
    ]

    operations = [
    ]
