# Generated by Django 5.1.3 on 2025-05-25 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0042_devicehistory_alter_employee_options'),
        ('inventory', '0041_update_employee_position_field'),
    ]

    operations = [
    ]
