# Generated by Django 5.1.3 on 2025-05-25 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0043_fix_position_reference'),
        ('inventory', '0043_merge_20250525_1418'),
    ]

    operations = [
    ]
