# Generated by Django 5.1.3 on 2025-05-26 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0047_fix_department_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
    ]
