# Generated by Django 5.1.3 on 2025-05-26 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0050_notification_system'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='inventory_n_employe_37314b_idx',
            old_name='inventory_n_employe_a440fc_idx',
        ),
    ]
