# Generated by Django 5.1.3 on 2025-05-26 07:55

from django.db import migrations

def create_default_categories(apps, schema_editor):
    NotificationCategory = apps.get_model('inventory', 'NotificationCategory')
    
    # Create default categories
    categories = [
        {
            'name': 'Device Assignment',
            'icon': 'fa-laptop',
            'color': 'primary',
            'description': 'Notifications related to device assignments and returns'
        },
        {
            'name': 'Maintenance',
            'icon': 'fa-wrench',
            'color': 'warning',
            'description': 'Notifications about device maintenance and repairs'
        },
        {
            'name': 'Warranty',
            'icon': 'fa-shield-alt',
            'color': 'info',
            'description': 'Notifications about warranty expiration and renewals'
        },
        {
            'name': 'System',
            'icon': 'fa-cog',
            'color': 'secondary',
            'description': 'System notifications and updates'
        },
        {
            'name': 'Alert',
            'icon': 'fa-exclamation-triangle',
            'color': 'danger',
            'description': 'Important alerts and critical notifications'
        }
    ]
    
    for category_data in categories:
        NotificationCategory.objects.create(**category_data)

def remove_default_categories(apps, schema_editor):
    NotificationCategory = apps.get_model('inventory', 'NotificationCategory')
    NotificationCategory.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0051_rename_inventory_n_employe_a440fc_idx_inventory_n_employe_37314b_idx'),
    ]

    operations = [
        migrations.RunPython(create_default_categories, remove_default_categories),
    ]
