"""
Django settings for inventory_app project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path
from django.utils.translation import gettext_lazy as _
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
# Load environment variables
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'insecure-dev-key')

# Error handling settings
HANDLER403 = 'inventory.handlers.handler403'

# Debug settings
DEBUG = os.getenv('DEBUG', 'True').lower() == 'true'
ALLOWED_HOSTS = [h.strip() for h in os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',') if h.strip()]

# CSRF Settings
CSRF_COOKIE_HTTPONLY = False  # Set to True if not using JavaScript to read the cookie
CSRF_TRUSTED_ORIGINS = [o.strip() for o in os.getenv('CSRF_TRUSTED_ORIGINS', 'http://localhost:8000,http://127.0.0.1:8000').split(',') if o.strip()]
CSRF_USE_SESSIONS = False  # Use cookie-based CSRF tokens
CSRF_COOKIE_SAMESITE = os.getenv('CSRF_COOKIE_SAMESITE', 'Lax')

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'inventory',  # Use the proper app config
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'inventory.middleware.SecurityMiddleware',
    'inventory.middleware.DataMaskingMiddleware',
]

# Session settings for enhanced security
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_COOKIE_AGE = 3600  # 1 hour
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_SAVE_EVERY_REQUEST = True  # Update the session on every request
SESSION_COOKIE_SECURE = not DEBUG  # Only send over HTTPS in production
SESSION_COOKIE_HTTPONLY = True  # Not accessible via JavaScript

# Security settings
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'
CSRF_COOKIE_SECURE = not DEBUG

# Custom settings for permission levels
PERMISSION_LEVELS = {
    'VIEW_ONLY': 1,
    'BASIC_OPERATIONS': 2,
    'FULL_ACCESS': 3,
    'ADMINISTRATIVE': 4,
}

# Operations requiring approval
OPERATIONS_REQUIRING_APPROVAL = [
    'delete',
    'bulk_update',
    'sensitive_access',
    'export',
    'permission_change',
]

# Sensitive fields that should be masked
SENSITIVE_FIELDS = [
    'national_id',
    'phone_number',
    'email',
    'mac_address_wifi',
    'mac_address_ethernet',
    'ip_address',
]

# Session validation settings
SESSION_VALIDATION_INTERVAL = 300  # 5 minutes
MAX_FAILED_LOGIN_ATTEMPTS = 5
FAILED_LOGIN_TIMEOUT = 3600  # 1 hour

# Permission Groups Configuration
PERMISSION_GROUPS = {
    'Read Only': {
        'can': ['view_*'],
        'cannot': ['add_*', 'change_*', 'delete_*'],
        'level': 1,
        'description': 'Can only view information, cannot make any changes'
    },
    'Basic User': {
        'can': ['view_*', 'add_*', 'change_*'],
        'cannot': [
            'delete_*',
            'add_user',
            'change_user',
            'delete_user',
            'add_group',
            'change_group',
            'delete_group'
        ],
        'level': 2,
        'description': 'Can view, add and edit basic information, cannot delete or manage users'
    },
    'Manager': {
        'can': ['view_*', 'add_*', 'change_*', 'delete_itasset', 'delete_employee'],
        'cannot': [
            'add_user',
            'change_user',
            'delete_user',
            'add_group',
            'change_group',
            'delete_group'
        ],
        'level': 3,
        'description': 'Can manage assets and employees, cannot manage system users'
    },
    'Admin': {
        'can': ['*'],
        'cannot': [],
        'level': 4,
        'description': 'Full system access'
    }
}

# New User Default Group
DEFAULT_NEW_USER_GROUP = 'Read Only'

# Operations that require approval
OPERATIONS_REQUIRING_APPROVAL = [
    'delete_user',
    'delete_itasset',
    'delete_employee',
    'bulk_delete',
    'bulk_update'
]

# Critical operations that need admin permission
CRITICAL_OPERATIONS = [
    'delete_user',
    'change_permissions',
    'add_group',
    'change_group',
    'delete_group'
]

ROOT_URLCONF = 'inventory_app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'inventory.context_processors.notification_context',
                'inventory.context_processors.superuser_check',
            ],
        },
    },
]

WSGI_APPLICATION = 'inventory_app.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME', 'inventory_db_it'),
        'USER': os.getenv('DB_USER', 'postgres'),
        'PASSWORD': os.getenv('DB_PASSWORD', ''),
        'HOST': os.getenv('DB_HOST', 'db'),  # Changed to 'db' for Docker
        'PORT': os.getenv('DB_PORT', '5432'),
        'CONN_MAX_AGE': 60,  # Keep connections alive
        'OPTIONS': {
            'connect_timeout': 5,
        }
    }
}

# Cache settings
if os.getenv('USE_REDIS', 'False').lower() == 'true':
    # Redis cache for production
    CACHES = {
        'default': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': os.getenv('REDIS_URL', 'redis://redis:6379/0'),
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            }
        }
    }
else:
    # Local memory cache for development
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'unique-snowflake',
        }
    }

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

# Authentication settings
LOGIN_URL = 'login'  # Use URL name instead of hardcoded path
LOGIN_REDIRECT_URL = 'inventory:home'  # Use URL name instead of hardcoded path
LOGOUT_REDIRECT_URL = 'landing'  # Use URL name instead of hardcoded path

# Default language
LANGUAGE_CODE = 'en'

# Available languages
LANGUAGES = [
    ('en', _('English')),
    ('ar', _('Arabic')),
]

# i18n settings
USE_I18N = True
USE_L10N = True
USE_TZ = True
TIME_ZONE = 'UTC'

# Locale paths
LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale'),
]

# URL settings
APPEND_SLASH = True
PREPEND_WWW = False

# Static files settings
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'inventory/static'),
]

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Email Settings for Password Reset
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'  # Replace with your SMTP server
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = ''  # Add your email
EMAIL_HOST_PASSWORD = ''  # Add your email password or app-specific password
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

